<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Menu</name>
   <tag></tag>
   <elementGuidId>f80c91df-1052-4a10-ba4b-f9ef64d1b112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.nav-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-top']/header/nav/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ebe733a6-960c-4702-85eb-373d9bc73226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-toggle</value>
      <webElementGuid>6aadbb50-7179-4d91-b676-cfe9a9ca0b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>nav-global-toggle</value>
      <webElementGuid>b08ec094-93b8-4243-829b-282db8ab027a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menu</value>
      <webElementGuid>a3e741cc-a31c-4098-83e8-0e86515885a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-top&quot;)/header[1]/nav[@class=&quot;nav-global&quot;]/label[@class=&quot;nav-toggle&quot;]</value>
      <webElementGuid>a51e0212-b19a-4ed2-a2de-536ad8e56b44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-top']/header/nav/label</value>
      <webElementGuid>eacef639-5ada-4f55-9aa2-84ebdbdf359f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Speakers'])[1]/preceding::label[1]</value>
      <webElementGuid>fcbc767c-6a80-4c92-94d0-023dfa971c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[1]/preceding::label[1]</value>
      <webElementGuid>ec466202-c390-40e3-b4be-d6a90fb6e64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menu']/parent::*</value>
      <webElementGuid>229c84d2-a4ed-4137-870a-f89d808060e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>76a1ad0d-8018-46ab-81a7-8b4add6c472d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Menu' or . = 'Menu')]</value>
      <webElementGuid>c920cc5e-4ff3-454d-8bbf-976862cc5f71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
