<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_fromName</name>
   <tag></tag>
   <elementGuidId>9a600541-d41e-4d98-8a40-6242d1746457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffca5623-c478-4e3e-b939-fe92df46052b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromName</value>
      <webElementGuid>98b57015-487c-4604-857b-ee9b0ffc9923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from-name</value>
      <webElementGuid>6eda8dc9-1835-472d-873b-d57edd13f8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1defdc98-4b3b-499b-b081-01365ab26895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Smith</value>
      <webElementGuid>5130b132-acec-4f7e-8bf6-572323a41e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from-name&quot;)</value>
      <webElementGuid>676f2bf1-4d9a-40c8-bdaf-b12861bee48e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from-name']</value>
      <webElementGuid>ca20e4c8-342b-4a8d-b047-b5af4682a1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>c4ea6199-e9fa-4e88-81df-e778cfa99582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'fromName' and @id = 'from-name' and @type = 'text' and @placeholder = 'Email Smith']</value>
      <webElementGuid>936c9d85-c7a2-4be4-8b58-9cab5b0ece12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
