<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If this is about a specific event, pl_49ece3</name>
   <tag></tag>
   <elementGuidId>ae2b0712-4d2f-46cc-a51b-172462178445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#which_event</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='which_event']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baa62f9c-f51e-4330-9296-a6144e3862ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message[Event]</value>
      <webElementGuid>95418a45-0d01-4082-b9b4-b5cf7af9d1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>which_event</value>
      <webElementGuid>9c188bc2-c8e4-4a7f-91d0-2bec6ea0e14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67607089-557f-4f64-84c8-303eabde40f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vladivostok 2112</value>
      <webElementGuid>15897326-8569-4485-b7bd-e9a451d56145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;which_event&quot;)</value>
      <webElementGuid>8066b69f-e022-4093-bac5-29a335b4dc08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='which_event']</value>
      <webElementGuid>a880be67-0594-41a0-acc2-e9c8cba6ec01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/input</value>
      <webElementGuid>51c8b4d8-3898-456a-9cd2-7baf287b5864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'message[Event]' and @id = 'which_event' and @type = 'text' and @placeholder = 'Vladivostok 2112']</value>
      <webElementGuid>5e5ba670-5fcd-4f93-a591-fcd96ec6246f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
