<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(required)_fromEmail</name>
   <tag></tag>
   <elementGuidId>8afc6e5f-89ba-47d5-921f-f22e27e20f5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#from-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='from-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c35ce8f-9141-4f70-af29-28e7b7361392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fromEmail</value>
      <webElementGuid>64ad4008-71fc-4204-a36d-dde110d48664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>from-email</value>
      <webElementGuid>32ae6e6f-aba7-4c26-a602-4b5dc4da5c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>81baeb74-2604-406f-8874-1b689de5e618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>email@example.com</value>
      <webElementGuid>bf240fb5-27f9-42e2-9b36-578de19a71dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;from-email&quot;)</value>
      <webElementGuid>f76819f2-5d07-4628-88de-cee47f9bfa46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='from-email']</value>
      <webElementGuid>1a32237c-c469-46c3-aaab-710b71ffd8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>41758f6e-4c3a-4401-9f46-99dcb73776ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'fromEmail' and @id = 'from-email' and @type = 'email' and @placeholder = 'email@example.com']</value>
      <webElementGuid>aa406fd3-846b-4e58-9508-366e89be2f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
