<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(required)_messagebody</name>
   <tag></tag>
   <elementGuidId>d1bfef45-a1d0-462d-a8b7-869081e9dc1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='user_message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2b10ef25-aec0-421f-a359-b047ddf931e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>659ab8bb-cfad-4ca2-a5b1-993fcf334bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-maxheight</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>15ac1205-745a-425b-a267-c89fa9349cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message[body]</value>
      <webElementGuid>bce6505e-eb7e-4193-92c4-e072e2a35e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_message</value>
      <webElementGuid>d9c4a27a-3161-4536-b42b-d3455726c418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_message&quot;)</value>
      <webElementGuid>7f889860-a93f-4483-be2a-723b847e6f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='user_message']</value>
      <webElementGuid>a246fdd3-8a57-48b7-80fd-101d5365045e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5db46d85-0107-4d07-9ad4-7d0e6a25b796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'message[body]' and @id = 'user_message']</value>
      <webElementGuid>2eaafa0a-46e8-4c4b-984c-6839a4a2bf93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
