<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_attendeecity</name>
   <tag></tag>
   <elementGuidId>5c099a0e-8b25-40a7-84d3-e6a447b44882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attendee_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attendee_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a14e3ce2-c2b3-4ada-8d7a-9531c40fb361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mediumInput</value>
      <webElementGuid>9b21653e-797d-4ee1-a265-3a14e5460266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>071be420-31f0-4013-a4d0-7878ed4cd8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attendee[city]</value>
      <webElementGuid>abc62612-3bd2-4906-9187-d76c90cb9946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attendee_city</value>
      <webElementGuid>ddffa6f3-c72e-4325-9ef2-9a729b11dbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendee_city&quot;)</value>
      <webElementGuid>63541792-aba2-492e-9f8e-e203158d5d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attendee_city']</value>
      <webElementGuid>9db4252e-7052-4fd2-afe1-18155eec1d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_attendee']/ol/li[5]/div/input</value>
      <webElementGuid>7147c0cb-48dd-4911-8b2c-b39266e7f8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/input</value>
      <webElementGuid>8ac311ca-3257-401d-a872-b6af16fa6439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'attendee[city]' and @id = 'attendee_city']</value>
      <webElementGuid>f425bd71-e4ea-4225-8931-713e46a62052</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
