<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suite_attendeesuite</name>
   <tag></tag>
   <elementGuidId>bae8016f-b7a4-44f1-8da4-b5f829b2d6c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attendee_suite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attendee_suite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>277d9123-df4b-44e6-bafb-c00dddec34b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shortInput</value>
      <webElementGuid>fa2c4b8a-05ad-4f74-83b0-441840b98249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>400217ad-9b5b-4db4-8e84-4df43800414b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attendee[suite]</value>
      <webElementGuid>fda2bfdb-7820-445c-b39f-300a8ce399a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attendee_suite</value>
      <webElementGuid>1f98d7a4-4717-4ae1-883e-2c4a2708adb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendee_suite&quot;)</value>
      <webElementGuid>676f7e33-99e2-440e-bfd2-474b4119af71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attendee_suite']</value>
      <webElementGuid>5a8da59e-3b73-47de-ace6-6234c8e39937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_attendee']/ol/li[4]/div[2]/input</value>
      <webElementGuid>23617159-9010-4ccf-aa41-cc1ed78fd589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/input</value>
      <webElementGuid>2cc8c03f-6db4-4c78-9ed7-663055267fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'attendee[suite]' and @id = 'attendee_suite']</value>
      <webElementGuid>16398cec-94c7-4ba6-9432-9d98bd608c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
