<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_attendeephone</name>
   <tag></tag>
   <elementGuidId>af8b6b9b-4649-4c13-85c9-5296d5fa2c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attendee_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attendee_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee50c1b1-9b07-4582-8baa-31357dced8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mediumInput</value>
      <webElementGuid>7226611f-979d-42cf-81f1-df611344e757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8fecbca-cf49-420c-a81e-97f928d19ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attendee[phone]</value>
      <webElementGuid>ab2214e9-131e-4463-86c6-1687755101be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attendee_phone</value>
      <webElementGuid>f4ac34ee-4b3c-49a7-b320-2fa1601637e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendee_phone&quot;)</value>
      <webElementGuid>ef21ba7d-d2bf-4e2c-b4bc-4dbabe689459</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attendee_phone']</value>
      <webElementGuid>ce31ef6d-3ba4-46a9-b5a7-d9d310753e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_attendee']/ol/li[8]/div/input</value>
      <webElementGuid>622fc755-f0ae-43e2-b078-0ce4e4c68cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/input</value>
      <webElementGuid>a5428b78-f52e-4952-ad62-3656bab2a1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'attendee[phone]' and @id = 'attendee_phone']</value>
      <webElementGuid>26ac51f0-96d4-4906-8386-aac4b2893968</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
