<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Has this person attended one of our p_a67947</name>
   <tag></tag>
   <elementGuidId>6fd1d60f-34f4-4800-95ec-ee3f35d36e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attendee_sponsor_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attendee_sponsor_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>003784af-98a0-4cb1-b9f1-ca4247c1378b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>labelGroup</value>
      <webElementGuid>ec22a474-5347-4342-9a8f-29506afe344d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6ac8fc39-8f97-4c21-8228-650fa9f485a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f7d00ade-c22a-4358-8594-1b0de358a5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attendee[sponsor_email]</value>
      <webElementGuid>63917347-6763-46b7-a596-aea2ebff48cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attendee_sponsor_email</value>
      <webElementGuid>2388298a-21bd-436a-a1af-342624f546eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendee_sponsor_email&quot;)</value>
      <webElementGuid>4c3d2178-dd80-4c20-b6dc-4b6d00ede35c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attendee_sponsor_email']</value>
      <webElementGuid>b1ae1965-a737-4215-8e14-713707052c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_attendee']/ol/li[10]/div/input[2]</value>
      <webElementGuid>396a124a-438f-48bb-89a6-3b40dc68d5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>4266c050-952e-442a-9b2b-211a260cab23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'attendee[sponsor_email]' and @id = 'attendee_sponsor_email']</value>
      <webElementGuid>ac3d4b87-fbb1-4597-9b4d-962d0304073f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
