<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_attendeelast_name</name>
   <tag></tag>
   <elementGuidId>bff97a72-6c07-4f3c-89c4-0f86c606fa35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attendee_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attendee_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6352f58d-babd-44f9-9d40-b916fcaea994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mediumInput</value>
      <webElementGuid>c023797b-40cb-41ab-8b7e-6b142eb9b7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e52e3c6-a452-4f85-bef7-2623601413f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attendee[last_name]</value>
      <webElementGuid>0773a56f-7931-4220-915e-5f4b252955d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attendee_last_name</value>
      <webElementGuid>c33ec2ea-d65a-492d-99fe-e02d6dfee2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendee_last_name&quot;)</value>
      <webElementGuid>c9f2a507-8b5d-4e90-bee5-63216f3bd3e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attendee_last_name']</value>
      <webElementGuid>ad49e923-58c6-4641-a4aa-91c0adc408a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_attendee']/ol/li/div[2]/input</value>
      <webElementGuid>878dfcc9-3ba0-4714-a54e-c917601fe862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f8b1d24c-6f44-4ec3-ab25-323e95795ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'attendee[last_name]' and @id = 'attendee_last_name']</value>
      <webElementGuid>a290e012-b6a3-471f-8c78-52d1d36e7044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
