<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_attendeeemail</name>
   <tag></tag>
   <elementGuidId>f6fa61cb-a53c-40cd-9b2c-8d48535a7996</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attendee_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attendee_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8eef0d74-9313-4d5b-b58c-f2d1324cbcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>longInput</value>
      <webElementGuid>a3304efe-2ade-47a8-8c30-fcd04d368d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6c8ae13-d06a-4090-a40b-b09a02076210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attendee[email]</value>
      <webElementGuid>1a5daede-c0d4-45d7-ad2d-5be533d64ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attendee_email</value>
      <webElementGuid>e33f7fdc-86b4-4d70-9f1c-36944327f60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendee_email&quot;)</value>
      <webElementGuid>8103046d-9fba-4b15-9869-42d98da9c5f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attendee_email']</value>
      <webElementGuid>25a0b89d-53fe-4107-b981-82dd29e1c794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_attendee']/ol/li[7]/div/input</value>
      <webElementGuid>eee36057-68ff-4483-aae2-6e0bf1200055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/input</value>
      <webElementGuid>3f51cc08-461a-4fc8-a77b-05d6659b98ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'attendee[email]' and @id = 'attendee_email']</value>
      <webElementGuid>20da150a-413a-44b0-b073-c055487488e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
