<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company_attendeecompany</name>
   <tag></tag>
   <elementGuidId>2cf6ccd0-c04d-4d58-bed0-ad4a41ddd747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attendee_company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attendee_company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>653751fb-cd3e-4b3a-a888-609c91b6370e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>longInput</value>
      <webElementGuid>56195c55-9404-44cb-8ffc-4b498f0b5a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c06d53b8-0ef4-4648-bd9b-ff7fbda3c66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attendee[company]</value>
      <webElementGuid>41fb82f4-a4ba-4d23-a48f-6638c3ca13aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attendee_company</value>
      <webElementGuid>c0d6f951-a529-4294-9f07-6551db82f570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendee_company&quot;)</value>
      <webElementGuid>69255f9a-c5b2-49dc-a639-656d839fda13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attendee_company']</value>
      <webElementGuid>1383de5c-b604-4697-acf4-2f7d0ee38cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_attendee']/ol/li[2]/div/input</value>
      <webElementGuid>d1670dcd-9214-4bad-aed4-9fac648a49d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/input</value>
      <webElementGuid>e4d35ad2-4557-4d32-800d-8e744100a873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'attendee[company]' and @id = 'attendee_company']</value>
      <webElementGuid>6a6fdf13-0a14-4e3f-8337-0fc0aa894c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
