<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Discount Code_attendeediscount_code</name>
   <tag></tag>
   <elementGuidId>cccd52c6-e7d3-4af6-8360-eb650d93312b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attendee_discount_code</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attendee_discount_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4be864ab-2955-4a52-8853-89cf45ba20c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>41768ac9-2955-4f50-9b29-78aacee6b2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3dee6ce5-0f97-4e2d-b5e9-a75890d8ea4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attendee[discount_code]</value>
      <webElementGuid>c97d0f23-48f4-421e-a849-f5a95b611cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attendee_discount_code</value>
      <webElementGuid>c773301f-1250-4a24-b1a5-1d346d7a82e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attendee_discount_code&quot;)</value>
      <webElementGuid>c6edc25b-3964-4f1d-98ae-88f5b686079a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attendee_discount_code']</value>
      <webElementGuid>d4204e33-0ee2-40fd-862b-d4825a38d295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_attendee']/ol/li[12]/div/input</value>
      <webElementGuid>a3835d5e-6309-482d-9c64-edec54b7dbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[12]/div/input</value>
      <webElementGuid>ddadbf06-fe8c-4cb7-bdd8-2e5adab89a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'attendee[discount_code]' and @id = 'attendee_discount_code']</value>
      <webElementGuid>7b16348e-9c79-4e89-b4a6-9bb9e17f4052</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
