<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy Now</name>
   <tag></tag>
   <elementGuidId>4c84a3cf-66e8-44c7-b4cc-6cc8590c23e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-ticket-pricing-1050</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='add-ticket-pricing-1050']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>559a9590-c422-42c7-9496-76afd26e5376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-ticket-pricing-1050</value>
      <webElementGuid>188e58a6-8a4f-4c6f-8295-07176bef470f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buy-link</value>
      <webElementGuid>39a4e959-b93b-45bb-83c8-5ba9825bfd13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cart/cart_tickets/new?ticket_pricing_id=1050</value>
      <webElementGuid>12e65131-37f9-41ad-9258-de958d6d3908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy Now!</value>
      <webElementGuid>be532c11-09a5-4f99-929d-14da7430ebf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-ticket-pricing-1050&quot;)</value>
      <webElementGuid>e96a85e5-47aa-4a28-b121-8523094d5cb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='add-ticket-pricing-1050']</value>
      <webElementGuid>8ba94089-0c63-4095-a2b4-d5d76815881d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='on-demand-three-day-pass']/footer/a</value>
      <webElementGuid>01a67edf-7d91-431b-be6a-00dfc39360e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buy Now!')]</value>
      <webElementGuid>26d77c1e-227b-461d-8fbc-8bbca69b7ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,050.00'])[2]/following::a[1]</value>
      <webElementGuid>5587b7dd-88e4-420e-9785-e0b57a3841a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,050.00'])[1]/following::a[1]</value>
      <webElementGuid>f3b0bee6-c6ba-43d7-bdf2-69ac16a431ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='April 18-19, 2022'])[1]/preceding::a[1]</value>
      <webElementGuid>da2cad4b-acab-408e-bd18-ac11e34525fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy Now!']/parent::*</value>
      <webElementGuid>92502d57-d08c-485f-938a-041631a0643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cart/cart_tickets/new?ticket_pricing_id=1050')]</value>
      <webElementGuid>55c6cc61-8beb-436c-ae0c-917399e3d065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/a</value>
      <webElementGuid>35339bc4-5794-40fe-8331-968dfb0d1677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'add-ticket-pricing-1050' and @href = '/cart/cart_tickets/new?ticket_pricing_id=1050' and (text() = 'Buy Now!' or . = 'Buy Now!')]</value>
      <webElementGuid>c1f72fcc-1719-4122-9f10-df24b30bd67c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
