<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Total1,050.00</name>
   <tag></tag>
   <elementGuidId>735b001b-f690-4c40-9921-4844ec4e158a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalcell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='totalcell']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6f71dff9-7c95-478e-a8f7-7f83d8baad86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>receiptSecondary receiptFigures</value>
      <webElementGuid>7f276cff-f4f0-4d8d-b5bc-6f31044e35a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalcell</value>
      <webElementGuid>c7c765a6-82df-42e9-bc6e-5a095070769d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total:$1,050.00</value>
      <webElementGuid>cf70ad23-6702-4163-a9da-466322055334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalcell&quot;)</value>
      <webElementGuid>45f181c5-45b4-4a3d-9a50-308d643d0465</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='totalcell']</value>
      <webElementGuid>180736bd-a583-4298-84f5-2dd476a62dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cart_total']/td[2]</value>
      <webElementGuid>a98f02ba-d56c-4348-9f12-3569e774b11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard Pass'])[1]/following::td[2]</value>
      <webElementGuid>91ccb68a-42ac-4194-ac7b-f8c95d0aa063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue Shopping'])[1]/preceding::td[1]</value>
      <webElementGuid>dc45e857-2808-48a4-8d12-f28359ff52ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>5e5280ea-bcf0-4682-998f-07f45de945a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'totalcell' and (text() = 'Total:$1,050.00' or . = 'Total:$1,050.00')]</value>
      <webElementGuid>c187b6b2-58ad-4806-8aa3-13b5e1b3ec38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
