<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Website_wp-comment-cookies-consent</name>
   <tag></tag>
   <elementGuidId>bd64366e-b3b8-4e12-9609-bf1354aa14db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wp-comment-cookies-consent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wp-comment-cookies-consent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8d9cde7-df4a-4028-b0e4-0f04b8792c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wp-comment-cookies-consent</value>
      <webElementGuid>efdd97e9-779a-4ea6-94b3-fc64875ef5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wp-comment-cookies-consent</value>
      <webElementGuid>32ecf198-5c18-4f99-ac92-a9c592eb65d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5714321-93d3-43a0-aac9-a38a5eb3c918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>3260dae6-6060-4b52-bb54-7ff711fec24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-comment-cookies-consent&quot;)</value>
      <webElementGuid>50b5a1e0-b6f7-4291-8ecd-8573ee7b7ba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wp-comment-cookies-consent']</value>
      <webElementGuid>9453b411-8cce-4889-8dd7-9f4d224a9241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commentform']/p[6]/input</value>
      <webElementGuid>016d90de-356f-44ba-ba17-b0cced5a177a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/input</value>
      <webElementGuid>5d8054a1-2abf-4f9b-a7a2-88179d143b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'wp-comment-cookies-consent' and @name = 'wp-comment-cookies-consent' and @type = 'checkbox']</value>
      <webElementGuid>afa52bd4-b91b-4f6b-b274-b6bd1bc244ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
